SET SQL DIALECT 3;

CREATE DATABASE 'F:\tanz\ARI\ARIBIRD.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1254;



/* Generators definitions */

CREATE GENERATOR AVANSLAR_AVANSLAR_KOD_GEN ;
CREATE GENERATOR EKIP_EKIPKODU_GEN ;
CREATE GENERATOR HARCAMALAR_HARCAMALAR_KOD_GEN ;
CREATE GENERATOR MASRAFLAR_MASRAFKOD_GEN ;
CREATE GENERATOR MUSTERI_MUSTERI_KOD_GEN ;
CREATE GENERATOR PERSONEL_PERSONELKOD_GEN ;
SET GENERATOR AVANSLAR_AVANSLAR_KOD_GEN TO 0;

SET GENERATOR EKIP_EKIPKODU_GEN TO 0;

SET GENERATOR HARCAMALAR_HARCAMALAR_KOD_GEN TO 0;

SET GENERATOR MASRAFLAR_MASRAFKOD_GEN TO 0;

SET GENERATOR MUSTERI_MUSTERI_KOD_GEN TO 0;

SET GENERATOR PERSONEL_PERSONELKOD_GEN TO 0;



/* Tables definitions */

CREATE TABLE AVANSLAR (
    AVANSLAR_KOD INTEGER NOT NULL,
    AVANSLAR_EKIPKOD INTEGER NOT NULL,
    AVANSLAR_TARIH DATE DEFAULT 'TODAY',
    AVANSLAR_MIKTAR NUMERIC (18, 0),
    AVANSLAR_MUSTERIKOD INTEGER);

CREATE TABLE EKIP (
    EKIPKODU INTEGER NOT NULL,
    EKIPAD VARCHAR (150) CHARACTER SET WIN1254 COLLATE PXW_TURK);

CREATE TABLE HARCAMALAR (
    HARCAMALAR_KOD INTEGER NOT NULL,
    HARCAMALAR_TARIH DATE DEFAULT 'TODAY' NOT NULL,
    HARCAMALAR_MUSTERIKODU INTEGER NOT NULL,
    HARCAMALAR_EKIPKODU INTEGER NOT NULL,
    HARCAMALAR_MASRAFKODU INTEGER NOT NULL,
    HARCAMALAR_MIKTAR NUMERIC (18, 0),
    HARCAMALAR_ACIKLAMA VARCHAR (150) CHARACTER SET WIN1254 COLLATE PXW_TURK);

CREATE TABLE MASRAFLAR (
    MASRAFKOD INTEGER NOT NULL,
    MASRAFAD VARCHAR (100) CHARACTER SET WIN1254 COLLATE PXW_TURK);

CREATE TABLE MUSTERI (
    MUSTERI_KOD INTEGER NOT NULL,
    MUSTERI_AD VARCHAR (100) CHARACTER SET WIN1254 NOT NULL COLLATE PXW_TURK,
    MUSTERI_VERGIDAIRESI VARCHAR (100) CHARACTER SET WIN1254 COLLATE PXW_TURK,
    MUSTERI_VERGINO VARCHAR (100) CHARACTER SET WIN1254 COLLATE PXW_TURK,
    MUSTERI_ADRES VARCHAR (100) CHARACTER SET WIN1254 COLLATE PXW_TURK,
    MUSTERI_GRUPKODU INTEGER);

CREATE TABLE PERSONEL (
    PERSONELKOD INTEGER NOT NULL,
    PERSONELADSOYAD VARCHAR (150) CHARACTER SET WIN1254 COLLATE PXW_TURK,
    PERSONELUNVAN VARCHAR (100) CHARACTER SET WIN1254 COLLATE PXW_TURK,
    PERSONELGRUPKODU INTEGER,
    PERSONELEKIPKODU INTEGER);



/* Primary keys definition */

ALTER TABLE AVANSLAR ADD CONSTRAINT PK_AVANSLAR PRIMARY KEY (AVANSLAR_KOD);
ALTER TABLE EKIP ADD CONSTRAINT PK_EKIP PRIMARY KEY (EKIPKODU);
ALTER TABLE HARCAMALAR ADD CONSTRAINT PK_HARCAMALAR PRIMARY KEY (HARCAMALAR_KOD);
ALTER TABLE MASRAFLAR ADD CONSTRAINT PK_MASRAFLAR PRIMARY KEY (MASRAFKOD);
ALTER TABLE MUSTERI ADD CONSTRAINT PK_MUSTERI PRIMARY KEY (MUSTERI_KOD);
ALTER TABLE PERSONEL ADD CONSTRAINT PK_PERSONEL PRIMARY KEY (PERSONELKOD);


/* Foreign keys definition */

ALTER TABLE AVANSLAR ADD CONSTRAINT FK_AVANSLAR_EKIPKOD FOREIGN KEY (AVANSLAR_EKIPKOD) REFERENCES EKIP (EKIPKODU) ON UPDATE CASCADE;
ALTER TABLE AVANSLAR ADD CONSTRAINT FK_AVANSLAR_MUSTERI FOREIGN KEY (AVANSLAR_MUSTERIKOD) REFERENCES MUSTERI (MUSTERI_KOD) ON UPDATE CASCADE;
ALTER TABLE HARCAMALAR ADD CONSTRAINT FK_HARCAMALAR_EKIP FOREIGN KEY (HARCAMALAR_EKIPKODU) REFERENCES EKIP (EKIPKODU) ON UPDATE CASCADE;
ALTER TABLE HARCAMALAR ADD CONSTRAINT FK_HARCAMALAR_MASRAFLAR FOREIGN KEY (HARCAMALAR_MASRAFKODU) REFERENCES MASRAFLAR (MASRAFKOD) ON UPDATE CASCADE;
ALTER TABLE HARCAMALAR ADD CONSTRAINT FK_HARCAMALAR_MUSTERI FOREIGN KEY (HARCAMALAR_MUSTERIKODU) REFERENCES MUSTERI (MUSTERI_KOD) ON UPDATE CASCADE;
ALTER TABLE PERSONEL ADD CONSTRAINT FK_PERSONEL_EKIP FOREIGN KEY (PERSONELEKIPKODU) REFERENCES EKIP (EKIPKODU) ON UPDATE CASCADE;


/* Indices definition */

CREATE INDEX FK_AVANSLAR_EKIPKOD ON AVANSLAR (AVANSLAR_EKIPKOD);
CREATE INDEX FK_AVANSLAR_MUSTERI ON AVANSLAR (AVANSLAR_MUSTERIKOD);
CREATE INDEX FK_HARCAMALAR_EKIP ON HARCAMALAR (HARCAMALAR_EKIPKODU);
CREATE INDEX FK_HARCAMALAR_MASRAFLAR ON HARCAMALAR (HARCAMALAR_MASRAFKODU);
CREATE INDEX FK_HARCAMALAR_MUSTERI ON HARCAMALAR (HARCAMALAR_MUSTERIKODU);
CREATE INDEX FK_PERSONEL_EKIP ON PERSONEL (PERSONELEKIPKODU);
CREATE UNIQUE INDEX PK_AVANSLAR ON AVANSLAR (AVANSLAR_KOD);
CREATE UNIQUE INDEX PK_EKIP ON EKIP (EKIPKODU);
CREATE UNIQUE INDEX PK_HARCAMALAR ON HARCAMALAR (HARCAMALAR_KOD);
CREATE UNIQUE INDEX PK_MASRAFLAR ON MASRAFLAR (MASRAFKOD);
CREATE UNIQUE INDEX PK_MUSTERI ON MUSTERI (MUSTERI_KOD);
CREATE UNIQUE INDEX PK_PERSONEL ON PERSONEL (PERSONELKOD);

SET TERM ^ ;

/* Triggers definition */



/* Trigger: AI_AVANSLAR_AVANSLAR_KOD */
CREATE TRIGGER AI_AVANSLAR_AVANSLAR_KOD FOR AVANSLAR ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.AVANSLAR_KOD IS NULL) THEN
      NEW.AVANSLAR_KOD = GEN_ID(AVANSLAR_AVANSLAR_KOD_GEN, 1);
END
^

/* Trigger: AI_EKIP_EKIPKODU */
CREATE TRIGGER AI_EKIP_EKIPKODU FOR EKIP ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.EKIPKODU IS NULL) THEN
      NEW.EKIPKODU = GEN_ID(EKIP_EKIPKODU_GEN, 1);
END
^

/* Trigger: AI_HARCAMALAR_HARCAMALAR_KOD */
CREATE TRIGGER AI_HARCAMALAR_HARCAMALAR_KOD FOR HARCAMALAR ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.HARCAMALAR_KOD IS NULL) THEN
      NEW.HARCAMALAR_KOD = GEN_ID(HARCAMALAR_HARCAMALAR_KOD_GEN, 1);
END
^

/* Trigger: AI_MASRAFLAR_MASRAFKOD */
CREATE TRIGGER AI_MASRAFLAR_MASRAFKOD FOR MASRAFLAR ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.MASRAFKOD IS NULL) THEN
      NEW.MASRAFKOD = GEN_ID(MASRAFLAR_MASRAFKOD_GEN, 1);
END
^

/* Trigger: AI_MUSTERI_MUSTERI_KOD */
CREATE TRIGGER AI_MUSTERI_MUSTERI_KOD FOR MUSTERI ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.MUSTERI_KOD IS NULL) THEN
      NEW.MUSTERI_KOD = GEN_ID(MUSTERI_MUSTERI_KOD_GEN, 1);
END
^

/* Trigger: AI_PERSONEL_PERSONELKOD */
CREATE TRIGGER AI_PERSONEL_PERSONELKOD FOR PERSONEL ACTIVE
BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.PERSONELKOD IS NULL) THEN
      NEW.PERSONELKOD = GEN_ID(PERSONEL_PERSONELKOD_GEN, 1);
END
^

SET TERM ; ^
