
/*------ 22.04.2004 10:16:51 --------*/

select
A.AVANSLAR_EKIPKOD,
A.AVANSLAR_KOD,
A.AVANSLAR_MIKTAR,
A.AVANSLAR_MUSTERIKOD,
A.AVANSLAR_TARIH,
E.EKIPAD,
M.MUSTERI_AD
from AVANSLAR A
JOIN EKIP E
ON E.EKIPKODU=A.AVANSLAR_EKIPKOD
JOIN MUSTERI M
ON M.MUSTERI_KOD = A.AVANSLAR_MUSTERIKOD

/*------ 22.04.2004 10:17:14 --------*/

select
A.AVANSLAR_EKIPKOD,
A.AVANSLAR_KOD,
A.AVANSLAR_MIKTAR,
A.AVANSLAR_MUSTERIKOD,
A.AVANSLAR_TARIH,
E.EKIPAD,
M.MUSTERI_AD
from AVANSLAR A
LEFT JOIN EKIP E
ON E.EKIPKODU=A.AVANSLAR_EKIPKOD
LEFT JOIN MUSTERI M
ON M.MUSTERI_KOD = A.AVANSLAR_MUSTERIKOD

/*------ 10:19:13 --------*/
ROLLBACK WORK

/*------ 22.04.2004 15:44:23 --------*/

select
PERSONELKOD,PERSONELADSOYAD
from PERSONEL
where PERSONELEKIPKODU = :EKIPKOD

/*------ 22.04.2004 15:44:31 --------*/

select
PERSONELKOD,PERSONELADSOYAD
from PERSONEL
where PERSONELEKIPKODU = :EKIPKOD

/*------ 22.04.2004 15:44:37 --------*/

select
PERSONELKOD,PERSONELADSOYAD
from PERSONEL
where PERSONELEKIPKODU = :EKIPKOD

/*------ 15:47:30 --------*/
ROLLBACK WORK

/*------ 22.04.2004 16:02:47 --------*/

delete from harcirah

/*------ 22.04.2004 16:02:50 --------*/

COMMIT WORK

/*------ 22.04.2004 16:04:16 --------*/

ALTER TABLE HARCIRAH DROP CONSTRAINT FK_HARCIRAH

/*------ 16:04:26 --------*/
COMMIT WORK

/*------ 16:04:37 --------*/
ROLLBACK WORK
